---
development:
  cloud_name: andrewburns16
  api_key: '476234217361529'
  api_secret: XHzMzps36hIF9xAFr3m4JN_p_Nk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: andrewburns16
  api_key: '476234217361529'
  api_secret: XHzMzps36hIF9xAFr3m4JN_p_Nk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: andrewburns16
  api_key: '476234217361529'
  api_secret: XHzMzps36hIF9xAFr3m4JN_p_Nk
  enhance_image_tag: true
  static_image_support: false
